jobs:
- template: common-pipelines.yml
  parameters:
    name: macOS
    vmImage: macOS-10.15

- template: common-pipelines.yml
  parameters:
    name: Linux
    vmImage: ubuntu-18.04

- template: common-pipelines.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016